title: "Gabriel Bizet"
email: "gabriel.bizet.etu@univ-lille.fr"
description: "Portfolio académique – Recherche, pratique clinique, enseignement"

theme: jekyll-theme-cayman

markdown: kramdown

# Déclaration de la collection des pages
collections:
  pages:
    output: true
    permalink: /:path/

# Valeurs par défaut pour toutes les pages de la collection
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

# Navigation du site
nav:
  - title: "Accueil"
    url: "/"
  - title: "À propos"
    url: "/about/"
  - title: "Pratique Clinique"
    url: "/pratique-clinique/"
  - title: "Recherche"
    url: "/recherche/"
  - title: "Enseignement"
    url: "/enseignement/"
  - title: "Cursus Académique"
    url: "/formation/"
  - title: "Projets Transversaux"
    url: "/projets-transversaux/"

sass:
  style: compressed

# Dossiers à inclure dans la génération
include:
  - assets
