title: "Gabriel Bizet"
email: "gabriel.bizet.etu@univ-lille.fr"
description: "Portfolio académique – Recherche, pratique clinique, enseignement"

remote_theme: pages-themes/primer@v0.6.0

markdown: kramdown

plugins:
  - jekyll-remote-theme


# Navigation du site
nav:
  - title: "Accueil"
    url: "/"
  - title: "À propos"
    url: "/about/"
  - title: "Pratique Clinique"
    url: "/pratique-clinique/"
  - title: "Recherche"
    url: "/recherche/"
  - title: "Enseignement"
    url: "/enseignement/"
  - title: "Cursus Académique"
    url: "/formation/"
  - title: "Projets Transversaux"
    url: "/projets-transversaux/"

sass:
  style: compressed

include:
  - assets
