title: "Gabriel Bizet"
email: "gabriel.bizet.etu@univ-lille.fr"
description: "Portfolio académique – Recherche, pratique clinique, enseignement"

remote_theme: pages-themes/primer@v0.6.0

markdown: kramdown

plugins:
  - jekyll-remote-theme

url: "https://hardwiredlab.github.io"
baseurl: "/gabrielbizet.github.io"

nav:
  - title: "Accueil"
    url: "{{ site.baseurl }}/"
  - title: "À propos"
    url: "{{ site.baseurl }}/about/"
  - title: "Pratique Clinique"
    url: "{{ site.baseurl }}/pratique-clinique/"
  - title: "Recherche"
    url: "{{ site.baseurl }}/recherche/"
  - title: "Enseignement"
    url: "{{ site.baseurl }}/enseignement/"
  - title: "Cursus Académique"
    url: "{{ site.baseurl }}/formation/"
  - title: "Projets Transversaux"
    url: "{{ site.baseurl }}/projets-transversaux/"
  - title: "Contact"
    url: "{{ site.baseurl }}/contact/"

sass:
  style: compressed

include:
  - assets
